apiVersion: build.openshift.io/v1
kind: Build
metadata:
  annotations:
    openshift.io/build-config.name: httpd-buildconfig
    openshift.io/build.number: "1"
    openshift.io/build.pod-name: initial-https-builder-build
  labels:
    buildconfig: httpd-buildconfig
    openshift.io/build-config.name: httpd-buildconfig
    openshift.io/build.start-policy: Serial
  name: initial-https-builder
  namespace: https-gitops-tester
spec:
  output:
    to:
      kind: ImageStreamTag
      name: httpd:downstream

  source:
    configMaps:
    - configMap:
        name: httpd-source-files
      destinationDir: public-html
    dockerfile: |-
      FROM registry.redhat.io/ubi9/httpd-24

      # Add application sources to a directory where the assemble script expects them
      # and set permissions so that the container runs without the root access
      USER 0
      ADD public-html/index.html /tmp/src/index.html
      RUN chown -R 1001:0 /tmp/src
      USER 1001

      # Let the assemble script install the dependencies
      RUN /usr/libexec/s2i/assemble

      # The run script uses standard ways to run the application
      CMD /usr/libexec/s2i/run
    type: Dockerfile

  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/httpd-24
    type: Docker

  triggeredBy:
  - message: Manually triggered
